[build]
  builder = "NIXPACKS"

[build.nixpacks]
  install_cmd = "npm install --prefix backend && npm install --prefix frontend"
  build_cmd = "cd frontend && CI=false npm run build"

[deploy]
  startCommand = "node backend/src/app.js"
  restartPolicyType = "ON_FAILURE"
  restartPolicyMaxRetries = 10
